blank_issues_enabled: true
contact_links:
  - name: 🆕 Create new issue
    url: https://github.com/nicelizhi/go-admin-api
    about: The issue which is not created via https://github.com/nicelizhi/go-admin-api will be closed immediately.
  - name: 🆕 创建一个新 Issue
    url: https://github.com/nicelizhi/go-admin-api
    about: 不是用 https://github.com/nicelizhi/go-admin-api 创建的 issue 会被机器人自动关闭。
