theme: jekyll-theme-cayman
show_downloads: true
title: Go Admin Service
description: Build a full-featured administrative interface quickly Go-Admin
lsi: false
safe: true
source: [/]
incremental: false
highlighter: rouge
page_excerpts: true
paginate: 5
site:
  categories: CATEGORY
  tags: TAG
  pages: []
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge